// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientProto/Attribute.proto

using wProtobuf;
using System.Collections;
using System.Collections.Generic;
using wProtobufRPC = wProtobuf.RPC;
using RPCILocalCall = wProtobuf.RPC.ILocalCall;
using RPCIRemoteCall = wProtobuf.RPC.IRemoteCall;

namespace NetProto
{
    public enum AttType
    {
        AT_Null = 0,
        AT_HP = 1,
        AT_MAX_HP = 3,
        AT_ZhenQi = 5,
        AT_LingLi = 6,
        AT_HuTi = 7,
        AT_Max_HuTi = 8,
        AT_QiLi = 9,
        AT_HuTiState = 10,
        AT_Posture = 11,
        AT_State = 13,
        AT_Speed = 15,
        AT_Level = 101,
        AT_Exp = 102,
        AT_Carrer = 103,
        AT_TeamID = 104,
        AT_Sex = 105,
        AT_TeamIsLeader = 106,
        AT_TeamLeaderUid = 107,
        AT_SilverShell = 108,
        AT_GoldShell = 109,
        AT_FairyJade = 110,
        AT_JasperJade = 111,
        AT_Energy = 112,
        AT_Organization = 113,
        AT_Chivalrous = 114,
        AT_Family = 115,
        AT_XiuWei = 116,
        AT_GongXun = 117,
        AT_Honor = 118,
        AT_TianPing = 119,
        AT_XinHuo = 120,
        AT_ClanId = 121,
        AT_ClanPost = 122,
        AT_ClanContributionAll = 123,
        AT_ClanContributionWeek = 124,
        AT_ClanResponeId = 125,
        AT_TotalAbilityScore = 126,
        AT_EquipAbilityScore = 127,
        AT_BloodPool = 128,
        AT_BloodBottle = 129,
        AT_AutoRestoreRate = 130,
        AT_PetBloodBottle = 131,
        AT_CombatPower = 132,
        AT_JoinClanTime = 133,
        AT_ClanLeagueTimes = 134,
        AT_ClanRunBusinessWeek = 135,
        AT_ClanRunBusinessAll = 136,
    }
}
