// Copyright (c) 2014 Marmoset LLC
//
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;

namespace mset {
	// Workaround for unity's serialization
	public class SHEncodingFile : ScriptableObject {
		public SHEncoding SH = null;
	}
}

