#if UNITY_EDITOR
using UnityEngine;
using UnityEditor;
using System.Collections.Generic;

namespace EditorExtensions
{
    /// <summary>
    /// EditorIconContent的枚举
    /// </summary>
    public enum EditorIconContentType
    {
        AS_Badge_Delete,
        AS_Badge_Move,
        AS_Badge_New,
        AboutWindow_MainHeader,
        AgeiaLogo,
        Animation_AddEvent,
        Animation_AddKeyframe,
        Animation_EventMarker,
        Animation_NextKey,
        Animation_Play,
        Animation_PrevKey,
        Animation_Record,
        AnimationWrapModeMenu,
        AnimatorController_Icon,
        AudioMixerController_Icon,
        Avatar_Icon,
        AvatarInspector_BodyPartPicker,
        AvatarInspector_BodySIlhouette,
        AvatarInspector_BodySilhouette,
        AvatarInspector_DotFill,
        AvatarInspector_DotFrame,
        AvatarInspector_DotFrameDotted,
        AvatarInspector_DotSelection,
        AvatarInspector_Head,
        AvatarInspector_HeadZoom,
        AvatarInspector_HeadZoomSilhouette,
        AvatarInspector_LeftArm,
        AvatarInspector_LeftFeetIk,
        AvatarInspector_LeftFingers,
        AvatarInspector_LeftFingersIk,
        AvatarInspector_LeftHandZoom,
        AvatarInspector_LeftHandZoomSilhouette,
        AvatarInspector_LeftLeg,
        AvatarInspector_MaskEditor_Root,
        AvatarInspector_RightArm,
        AvatarInspector_RightFeetIk,
        AvatarInspector_RightFingers,
        AvatarInspector_RightFingersIk,
        AvatarInspector_RightHandZoom,
        AvatarInspector_RightHandZoomSilhouette,
        AvatarInspector_RightLeg,
        AvatarInspector_Torso,
        AvatarPivot,
        BuildSettings_Android,
        BuildSettings_Editor,
        BuildSettings_Metro,
        BuildSettings_N3DS,
        BuildSettings_PS3,
        BuildSettings_PS4,
        BuildSettings_PSP2,
        BuildSettings_SamsungTV,
        BuildSettings_SelectedIcon,
        BuildSettings_Standalone,
        BuildSettings_StandaloneGLESEmu,
        BuildSettings_Tizen,
        BuildSettings_Web,
        BuildSettings_Web_Small,
        BuildSettings_WebGL,
        BuildSettings_WebGL_Small,
        BuildSettings_WiiU,
        BuildSettings_XBox360,
        BuildSettings_XboxOne,
        BuildSettings_iPhone,
        BuildSettings_tvOS,
        Camera_Icon,
        Clipboard,
        ClothInspector_PaintValue,
        CloudConnect,
        ColorPicker_CycleColor,
        ColorPicker_CycleSlider,
        EditCollider,
        EyeDropper_Large,
        GUISystem_align_horizontally_center,
        GUISystem_align_horizontally_center_active,
        GUISystem_align_horizontally_left,
        GUISystem_align_horizontally_left_active,
        GUISystem_align_horizontally_right,
        GUISystem_align_horizontally_right_active,
        GUISystem_align_vertically_bottom,
        GUISystem_align_vertically_bottom_active,
        GUISystem_align_vertically_center,
        GUISystem_align_vertically_center_active,
        GUISystem_align_vertically_top,
        GUISystem_align_vertically_top_active,
        GameObject_Icon,
        HorizontalSplit,
        Icon_Dropdown,
        MeshRenderer_Icon,
        Mirror,
        MonoLogo,
        MoveTool_On,
        MoveTool,
        PauseButton_Anim,
        PauseButton_On,
        PauseButton,
        PlayButton_Anim,
        PlayButton_On,
        PlayButton,
        PlayButtonProfile_Anim,
        PlayButtonProfile_On,
        PlayButtonProfile,
        PreMatCube,
        PreMatCylinder,
        PreMatLight0,
        PreMatLight1,
        PreMatQuad,
        PreMatSphere,
        PreMatTorus,
        PreTextureAlpha,
        PreTextureMipMapHigh,
        PreTextureMipMapLow,
        PreTextureRGB,
        Prefab_Icon,
        PrefabModel_Icon,
        PrefabNormal_Icon,
        Profiler_NextFrame,
        Profiler_PrevFrame,
        Profiler_Record,
        RectTool_On,
        RectTool,
        RectTransformBlueprint,
        RectTransformRaw,
        RotateTool_On,
        RotateTool,
        ScaleTool_On,
        ScaleTool,
        SceneviewAudio,
        SceneviewFx,
        SceneviewLighting,
        ScriptableObject_Icon,
        Search,
        SettingsIcon,
        Shader_Icon,
        SocialNetworks_FacebookShare,
        SocialNetworks_LinkedInShare,
        SocialNetworks_Tweet,
        SocialNetworks_UDNLogo,
        SocialNetworks_UDNOpen,
        SpeedScale,
        Sprite_Icon,
        StepButton_Anim,
        StepButton_On,
        StepButton,
        Terrain_Icon,
        TerrainInspector_TerrainToolPlants,
        TerrainInspector_TerrainToolRaise,
        TerrainInspector_TerrainToolSetHeight,
        TerrainInspector_TerrainToolSettings,
        TerrainInspector_TerrainToolSmoothHeight,
        TerrainInspector_TerrainToolSplat,
        TerrainInspector_TerrainToolTrees,
        TestFailed,
        TestIgnored,
        TestInconclusive,
        TestNormal,
        TestPassed,
        TextAsset_Icon,
        Toolbar_Minus,
        Toolbar_Plus_More,
        Toolbar_Plus,
        TreeEditor_AddBranches,
        TreeEditor_AddLeaves,
        TreeEditor_BranchFreeHand,
        TreeEditor_BranchRotate,
        TreeEditor_BranchTranslate,
        TreeEditor_Duplicate,
        TreeEditor_LeafRotate,
        TreeEditor_LeafTranslate,
        TreeEditor_Refresh,
        TreeEditor_Trash,
        UnityLogo,
        VerticalSplit,
        ViewToolMove_On,
        ViewToolMove,
        ViewToolOrbit_On,
        ViewToolOrbit,
        ViewToolZoom_On,
        ViewToolZoom,
        WaitSpin00,
        WaitSpin01,
        WaitSpin02,
        WaitSpin03,
        WaitSpin04,
        WaitSpin05,
        WaitSpin06,
        WaitSpin07,
        WaitSpin08,
        WaitSpin09,
        WaitSpin10,
        WaitSpin11,
        WelcomeScreen_AssetStoreLogo,
        WelcomeScreen_MainHeader,
        WelcomeScreen_UnityAnswersLogo,
        WelcomeScreen_UnityBasicsLogo,
        WelcomeScreen_UnityForumLogo,
        WelcomeScreen_VideoTutLogo,
        animationvisibilitytoggleoff,
        animationvisibilitytoggleon,
        blendKey,
        boo_Script_Icon,
        console_erroricon,
        console_erroricon_sml,
        console_infoicon,
        console_warnicon,
        cs_Script_Icon,
        editicon_sml,
        js_Script_Icon,
        lightMeter_greenLight,
        lightMeter_lightRim,
        lightMeter_orangeLight,
        lightMeter_redLight,
        playLoopOff,
        preAudioAutoPlayOff,
        preAudioAutoPlayOn,
        preAudioLoopOff,
        preAudioLoopOn,
        preAudioPlayOff,
        preAudioPlayOn,
        renderdoc,
        sv_icon_dot0_pix16_gizmo,
        sv_icon_dot0_sml,
        sv_icon_dot10_pix16_gizmo,
        sv_icon_dot10_sml,
        sv_icon_dot11_pix16_gizmo,
        sv_icon_dot11_sml,
        sv_icon_dot12_pix16_gizmo,
        sv_icon_dot12_sml,
        sv_icon_dot13_pix16_gizmo,
        sv_icon_dot13_sml,
        sv_icon_dot14_pix16_gizmo,
        sv_icon_dot14_sml,
        sv_icon_dot15_pix16_gizmo,
        sv_icon_dot15_sml,
        sv_icon_dot1_pix16_gizmo,
        sv_icon_dot1_sml,
        sv_icon_dot2_pix16_gizmo,
        sv_icon_dot2_sml,
        sv_icon_dot3_pix16_gizmo,
        sv_icon_dot3_sml,
        sv_icon_dot4_pix16_gizmo,
        sv_icon_dot4_sml,
        sv_icon_dot5_pix16_gizmo,
        sv_icon_dot5_sml,
        sv_icon_dot6_pix16_gizmo,
        sv_icon_dot6_sml,
        sv_icon_dot7_pix16_gizmo,
        sv_icon_dot7_sml,
        sv_icon_dot8_pix16_gizmo,
        sv_icon_dot8_sml,
        sv_icon_dot9_pix16_gizmo,
        sv_icon_dot9_sml,
        sv_icon_name0,
        sv_icon_name1,
        sv_icon_name2,
        sv_icon_name3,
        sv_icon_name4,
        sv_icon_name5,
        sv_icon_name6,
        sv_icon_name7,
        sv_icon_none,
        sv_label_0,
        sv_label_1,
        sv_label_2,
        sv_label_3,
        sv_label_4,
        sv_label_5,
        sv_label_6,
        sv_label_7,
        tree_icon,
        tree_icon_branch,
        tree_icon_branch_frond,
        tree_icon_frond,
        tree_icon_leaf,
    }

    public class EditorIconContent
    {
        
        // GUIContent缓存，key为图片名
        static Dictionary<string, GUIContent> _iconContentCache = new Dictionary<string, GUIContent>();

        /// <summary>
        /// 数量
        /// </summary>
        public static int Count
        {
            get { return _iconContentCache.Count; }
        }

        /// <summary>
        /// 自定义GUIContent（这个只是参考）
        /// </summary>
        public static GUIContent CustomContent
        {
            get
            {
                GUIContent content = Get("CustomContent");
                return content;
            }
        }

        /// <summary>
        /// 获取GUIContent
        /// </summary>
        /// <param name="imageName"></param>
        /// <param name="text"></param>
        /// <param name="tips"></param>
        /// <returns></returns>
        public static GUIContent Get(string imageName, string text, string tips)
        {
            if (_iconContentCache.ContainsKey(imageName))
            {
                return _iconContentCache[imageName];
            }
            GUIContent content = new GUIContent(text, EditorIconTexture.GetCustom(imageName), tips);
            _iconContentCache.Add (imageName, content);
            return content;
        }

        public static GUIContent Get(string imageName, string text)
        {
            if (_iconContentCache.ContainsKey(imageName))
            {
                return _iconContentCache[imageName];
            }
            GUIContent content = new GUIContent(text, EditorIconTexture.GetCustom(imageName));
            _iconContentCache.Add(imageName, content);
            return content;
        }

        public static GUIContent Get(string imageName)
        {
            if (_iconContentCache.ContainsKey(imageName))
            {
                return _iconContentCache[imageName];
            }
            GUIContent content = new GUIContent(EditorIconTexture.GetCustom(imageName));
            _iconContentCache.Add(imageName, content);
            return content;
        }

        public static GUIContent Get(IconTextureType imageType)
        {
            if (_iconContentCache.ContainsKey(imageType.ToString()))
            {
                return _iconContentCache[imageType.ToString()];
            }
            GUIContent content = new GUIContent(EditorIconTexture.GetSystem(imageType));
            _iconContentCache.Add(imageType.ToString(), content);
            return content;
        }

        /// <summary>
        /// 获取系统自带的GUIContent
        /// </summary>
        /// <param name="iconType"></param>
        /// <returns></returns>
        public static GUIContent GetSystem(EditorIconContentType iconType)
        {
            string name = _IconContentNames[(int)iconType];
            if (_iconContentCache.ContainsKey(name))
                return _iconContentCache[name];

            GUIContent content = EditorGUIUtility.IconContent(name);
            _iconContentCache.Add (name, content);
            return content;
        }

#region EditorIconContentNames

        static string[] _IconContentNames ={
            "AS Badge Delete",
            "AS Badge Move",
            "AS Badge New",
            "AboutWindow.MainHeader",
            "AgeiaLogo",
            "Animation.AddEvent",
            "Animation.AddKeyframe",
            "Animation.EventMarker",
            "Animation.NextKey",
            "Animation.Play",
            "Animation.PrevKey",
            "Animation.Record",
            "AnimationWrapModeMenu",
            "AnimatorController Icon",
            "AudioMixerController Icon",
            "Avatar Icon",
            "AvatarInspector/BodyPartPicker",
            "AvatarInspector/BodySIlhouette",
            "AvatarInspector/BodySilhouette",
            "AvatarInspector/DotFill",
            "AvatarInspector/DotFrame",
            "AvatarInspector/DotFrameDotted",
            "AvatarInspector/DotSelection",
            "AvatarInspector/Head",
            "AvatarInspector/HeadZoom",
            "AvatarInspector/HeadZoomSilhouette",
            "AvatarInspector/LeftArm",
            "AvatarInspector/LeftFeetIk",
            "AvatarInspector/LeftFingers",
            "AvatarInspector/LeftFingersIk",
            "AvatarInspector/LeftHandZoom",
            "AvatarInspector/LeftHandZoomSilhouette",
            "AvatarInspector/LeftLeg",
            "AvatarInspector/MaskEditor_Root",
            "AvatarInspector/RightArm",
            "AvatarInspector/RightFeetIk",
            "AvatarInspector/RightFingers",
            "AvatarInspector/RightFingersIk",
            "AvatarInspector/RightHandZoom",
            "AvatarInspector/RightHandZoomSilhouette",
            "AvatarInspector/RightLeg",
            "AvatarInspector/Torso",
            "AvatarPivot",
            "BuildSettings.Android",
            "BuildSettings.Editor",
            "BuildSettings.Metro",
            "BuildSettings.N3DS",
            "BuildSettings.PS3",
            "BuildSettings.PS4",
            "BuildSettings.PSP2",
            "BuildSettings.SamsungTV",
            "BuildSettings.SelectedIcon",
            "BuildSettings.Standalone",
            "BuildSettings.StandaloneGLESEmu",
            "BuildSettings.Tizen",
            "BuildSettings.Web",
            "BuildSettings.Web.Small",
            "BuildSettings.WebGL",
            "BuildSettings.WebGL.Small",
            "BuildSettings.WiiU",
            "BuildSettings.XBox360",
            "BuildSettings.XboxOne",
            "BuildSettings.iPhone",
            "BuildSettings.tvOS",
            "Camera Icon",
            "Clipboard",
            "ClothInspector.PaintValue",
            "CloudConnect",
            "ColorPicker.CycleColor",
            "ColorPicker.CycleSlider",
            "EditCollider",
            "EyeDropper.Large",
            "GUISystem/align_horizontally_center",
            "GUISystem/align_horizontally_center_active",
            "GUISystem/align_horizontally_left",
            "GUISystem/align_horizontally_left_active",
            "GUISystem/align_horizontally_right",
            "GUISystem/align_horizontally_right_active",
            "GUISystem/align_vertically_bottom",
            "GUISystem/align_vertically_bottom_active",
            "GUISystem/align_vertically_center",
            "GUISystem/align_vertically_center_active",
            "GUISystem/align_vertically_top",
            "GUISystem/align_vertically_top_active",
            "GameObject Icon",
            "HorizontalSplit",
            "Icon Dropdown",
            "MeshRenderer Icon",
            "Mirror",
            "MonoLogo",
            "MoveTool On",
            "MoveTool",
            "PauseButton Anim",
            "PauseButton On",
            "PauseButton",
            "PlayButton Anim",
            "PlayButton On",
            "PlayButton",
            "PlayButtonProfile Anim",
            "PlayButtonProfile On",
            "PlayButtonProfile",
            "PreMatCube",
            "PreMatCylinder",
            "PreMatLight0",
            "PreMatLight1",
            "PreMatQuad",
            "PreMatSphere",
            "PreMatTorus",
            "PreTextureAlpha",
            "PreTextureMipMapHigh",
            "PreTextureMipMapLow",
            "PreTextureRGB",
            "Prefab Icon",
            "PrefabModel Icon",
            "PrefabNormal Icon",
            "Profiler.NextFrame",
            "Profiler.PrevFrame",
            "Profiler.Record",
            "RectTool On",
            "RectTool",
            "RectTransformBlueprint",
            "RectTransformRaw",
            "RotateTool On",
            "RotateTool",
            "ScaleTool On",
            "ScaleTool",
            "SceneviewAudio",
            "SceneviewFx",
            "SceneviewLighting",
            "ScriptableObject Icon",
            "Search",
            "SettingsIcon",
            "Shader Icon",
            "SocialNetworks.FacebookShare",
            "SocialNetworks.LinkedInShare",
            "SocialNetworks.Tweet",
            "SocialNetworks.UDNLogo",
            "SocialNetworks.UDNOpen",
            "SpeedScale",
            "Sprite Icon",
            "StepButton Anim",
            "StepButton On",
            "StepButton",
            "Terrain Icon",
            "TerrainInspector.TerrainToolPlants",
            "TerrainInspector.TerrainToolRaise",
            "TerrainInspector.TerrainToolSetHeight",
            "TerrainInspector.TerrainToolSettings",
            "TerrainInspector.TerrainToolSmoothHeight",
            "TerrainInspector.TerrainToolSplat",
            "TerrainInspector.TerrainToolTrees",
            "TestFailed",
            "TestIgnored",
            "TestInconclusive",
            "TestNormal",
            "TestPassed",
            "TextAsset Icon",
            "Toolbar Minus",
            "Toolbar Plus More",
            "Toolbar Plus",
            "TreeEditor.AddBranches",
            "TreeEditor.AddLeaves",
            "TreeEditor.BranchFreeHand",
            "TreeEditor.BranchRotate",
            "TreeEditor.BranchTranslate",
            "TreeEditor.Duplicate",
            "TreeEditor.LeafRotate",
            "TreeEditor.LeafTranslate",
            "TreeEditor.Refresh",
            "TreeEditor.Trash",
            "UnityLogo",
            "VerticalSplit",
            "ViewToolMove On",
            "ViewToolMove",
            "ViewToolOrbit On",
            "ViewToolOrbit",
            "ViewToolZoom On",
            "ViewToolZoom",
            "WaitSpin00",
            "WaitSpin01",
            "WaitSpin02",
            "WaitSpin03",
            "WaitSpin04",
            "WaitSpin05",
            "WaitSpin06",
            "WaitSpin07",
            "WaitSpin08",
            "WaitSpin09",
            "WaitSpin10",
            "WaitSpin11",
            "WelcomeScreen.AssetStoreLogo",
            "WelcomeScreen.MainHeader",
            "WelcomeScreen.UnityAnswersLogo",
            "WelcomeScreen.UnityBasicsLogo",
            "WelcomeScreen.UnityForumLogo",
            "WelcomeScreen.VideoTutLogo",
            "animationvisibilitytoggleoff",
            "animationvisibilitytoggleon",
            "blendKey",
            "boo Script Icon",
            "console.erroricon",
            "console.erroricon.sml",
            "console.infoicon",
            "console.warnicon",
            "cs Script Icon",
            "editicon.sml",
            "js Script Icon",
            "lightMeter/greenLight",
            "lightMeter/lightRim",
            "lightMeter/orangeLight",
            "lightMeter/redLight",
            "playLoopOff",
            "preAudioAutoPlayOff",
            "preAudioAutoPlayOn",
            "preAudioLoopOff",
            "preAudioLoopOn",
            "preAudioPlayOff",
            "preAudioPlayOn",
            "renderdoc",
            "sv_icon_dot0_pix16_gizmo",
            "sv_icon_dot0_sml",
            "sv_icon_dot10_pix16_gizmo",
            "sv_icon_dot10_sml",
            "sv_icon_dot11_pix16_gizmo",
            "sv_icon_dot11_sml",
            "sv_icon_dot12_pix16_gizmo",
            "sv_icon_dot12_sml",
            "sv_icon_dot13_pix16_gizmo",
            "sv_icon_dot13_sml",
            "sv_icon_dot14_pix16_gizmo",
            "sv_icon_dot14_sml",
            "sv_icon_dot15_pix16_gizmo",
            "sv_icon_dot15_sml",
            "sv_icon_dot1_pix16_gizmo",
            "sv_icon_dot1_sml",
            "sv_icon_dot2_pix16_gizmo",
            "sv_icon_dot2_sml",
            "sv_icon_dot3_pix16_gizmo",
            "sv_icon_dot3_sml",
            "sv_icon_dot4_pix16_gizmo",
            "sv_icon_dot4_sml",
            "sv_icon_dot5_pix16_gizmo",
            "sv_icon_dot5_sml",
            "sv_icon_dot6_pix16_gizmo",
            "sv_icon_dot6_sml",
            "sv_icon_dot7_pix16_gizmo",
            "sv_icon_dot7_sml",
            "sv_icon_dot8_pix16_gizmo",
            "sv_icon_dot8_sml",
            "sv_icon_dot9_pix16_gizmo",
            "sv_icon_dot9_sml",
            "sv_icon_name0",
            "sv_icon_name1",
            "sv_icon_name2",
            "sv_icon_name3",
            "sv_icon_name4",
            "sv_icon_name5",
            "sv_icon_name6",
            "sv_icon_name7",
            "sv_icon_none",
            "sv_label_0",
            "sv_label_1",
            "sv_label_2",
            "sv_label_3",
            "sv_label_4",
            "sv_label_5",
            "sv_label_6",
            "sv_label_7",
            "tree_icon",
            "tree_icon_branch",
            "tree_icon_branch_frond",
            "tree_icon_frond",
            "tree_icon_leaf"};

#endregion
    }
}
#endif